<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TranslationService.Contracts\TranslationService.Contracts.csproj" />
    <ProjectReference Include="..\TranslationService.Domain\TranslationService.Domain.csproj" />
  </ItemGroup>

</Project>
